= Nim basics
:source-highlighter: rouge
:rouge-style: gruvbox
:source-language: nim
:source-dir: code
:icons: font
:stylesheet: style.css
:linkcss:
:doctype: book
:toc: left
:nofooter:


https://nim-lang.org/[Nim] jest relatywnie nowym jezykiem programowania ktory pozwala uzytkownikom na pisanie latwego w odczycie wysoko wydajnego kodu.
Jezeli jednak czytasz ten samouczek, sa szanse, ze wiesz juz co nieco o tym jezyku.

Anglojezyczna wersja samouczka jest dostepna https://narimiran.github.io/nim-basics/[online] oraz jako plik https://github.com/narimiran/nim-basics/raw/master/nim-basics.pdf[PDF].

Samouczek jest caly czas rozwijany: jesli zauwazysz jakies bledy i/lub masz pomysl jak uczynic go lepszym, zglos to do https://github.com/narimiran/nim-basics/issues[issue tracker].




== Kto skorzysta z tego materialu?

* Osoby bez lub z minimalnym wczesniejszym doswiadczeniem w programowaniu
* Osoby z niewielkim doswiadczeniem z innymi jezykami
* Osoby ktore chca poznac jezyk Nime zaczynajac od podstaw


== Kto __nie skorzysta__ z tego materialu?

* Osoby ze sporym doswiadczeniem programistycznym: inne, bardziej zaawansowane, przewodniki moga Tobie bardziej pasowac. Zobacz https://nim-lang.org/docs/tut1.html[Official Tutorial] or https://nim-by-example.github.io/[Nim by Example].
* Osoby z doswiadczeniem w jezyku Nim (pomozcie ulepszyc ten samouczek)


== Jak korzystac z tego samouczka?

Celem tego tekstu jest nauczenie Ciebie podstaw programowania i skladni jezyka Nim aby bylo Tobie latwiej rozumiec inne, bardziej zaawansowane materialy i/lub poznawac jezyk samodzielnie.

Zamiast tylko czytac, najlepiej byloby gdybys samodzielnie wpisywal kod oraz modyfikowal przyklady, zastanawial sie nad nimi, i ogolnie mowiac - byl ciekawy.
Cwiczenia na koncu niektorych rozdzialow powinny byc wykonane aby utrwalic poznane zagadnienia -- pamietaj o nich.

Jezeli potrzebujesz dodatkowej pomocy w zrozumieniu jakis czesci tego materialu albo z cwiczeniami, mozesz zawsze poprosic o pomoc korzystajac z https://forum.nim-lang.org/[Forum], the https://gitter.im/nim-lang/Nim[Kanalu Gitter ], https://discordapp.com/invite/ezDFDw2[serwera Discord ], lub kanalu IRC na serwerze freenode, #nim.


include::01-installation.adoc[]

include::02-variables.adoc[]

include::03-types.adoc[]

include::04-control-flow.adoc[]

include::05-loops.adoc[]

include::06-containers.adoc[]

include::07-procedures.adoc[]

include::08-modules.adoc[]

include::09-user-input.adoc[]

include::10-conclusion.adoc[]


{nbsp}

{nbsp}

'''

{nbsp}

The source files are available https://github.com/narimiran/nim-basics[on Github].
