= Nim - podstawy języka
:source-highlighter: rouge
:rouge-style: gruvbox
:source-language: nim
:source-dir: code
:icons: font
:stylesheet: style.css
:linkcss:
:doctype: book
:toc: left
:nofooter:


https://nim-lang.org/[Nim] jest relatywnie nowym językiem programowania który pozwala użytkownikom na pisanie łatwego w odczycie wysoko wydajnego kodu.
Jeżeli jednak czytasz ten samouczek, są szanse, że wiesz już co nieco o tym języku.

Anglojęzyczna wersja samouczka jest dostępna https://narimiran.github.io/nim-basics/[online] oraz jako plik https://github.com/narimiran/nim-basics/raw/master/nim-basics.pdf[PDF].

Samouczek jest caly czas rozwijany: jeśli zauważysz jakieś błedy i/lub masz pomysł jak uczynić go lepszym, zgloś to do https://github.com/narimiran/nim-basics/issues[systemu śledzącego].




== Kto skorzysta z tego materiału?

* Osoby bez lub z minimalnym wcześniejszym doświadczeniem w programowaniu
* Osoby z niewielkim doświadczeniem z innymi jezykami
* Osoby które chcą poznac język Nim zaczynając od podstaw


== Kto __nie skorzysta__ z tego materiału?

* Osoby ze sporym doświadczeniem programistycznym: inne, bardziej zaawansowane, przewodniki mogą Tobie bardziej pasować. Zobacz https://nim-lang.org/docs/tut1.html[Oficjalny Tutorial] or https://nim-by-example.github.io/[Nim w przykładach].
* Osoby z doświadczeniem w jezyku Nim (pomożcie ulepszyc ten samouczek)


== Jak korzystać z tego kursu?

Celem tego tekstu jest nauczenie Ciebie podstaw programowania i składni języka Nim aby było Tobie łatwiej rozumieć inne, bardziej zaawansowane materiały i/lub poznawać jezyk samodzielnie.

Zamiast tylko czytać, najlepiej byłoby gdybyś samodzielnie wpisywał kod oraz modyfikował przyklady, zastanawiał się nad nimi, i ogólnie mówiąc - był ciekawy.
Ćwiczenia na końcu niektórych rozdziałów powinny być wykonane aby utrwalić poznane zagadnienia -- pamietaj o nich.

Jeżeli potrzebujesz dodatkowej pomocy w zrozumieniu jakiś części tego materiału albo z ćwiczeniami, możesz zawsze poprosić o pomoc korzystając z https://forum.nim-lang.org/[Forum], the https://gitter.im/nim-lang/Nim[kanału Gitter ], https://discordapp.com/invite/ezDFDw2[serwera Discord ], lub kanału IRC na serwerze freenode, #nim.


include::01-installation.adoc[]

include::02-variables.adoc[]

include::03-types.adoc[]

include::04-control-flow.adoc[]

include::05-loops.adoc[]

include::06-containers.adoc[]

include::07-procedures.adoc[]

include::08-modules.adoc[]

include::09-user-input.adoc[]

include::10-conclusion.adoc[]


{nbsp}

{nbsp}

'''

{nbsp}

The source files are available https://github.com/narimiran/nim-basics[on Github].
