= Instalacja



== Instalacja języka Nim

Nim posiada gotowe pakiety dystrybucyjne dla trzech głównych systemów operacyjnych oraz kilka sposobów na instalację języka.

Możesz skorzystać z  https://nim-lang.org/install.html[oficjalnej procedury instalacji] aby zainstalować najnowszą stabilną wersję, lub użyć narzędzia https://github.com/dom96/choosenim[choosenim] które pozwala na łatwe przełączanie się pomiędzy wersją stabliną a najnowszą wersją rozwojową, jeżeli jesteś zaintersowany nowościami i poprawkami błędów.

Jakikolwiek sposób wybierzesz, podążaj według wskazówek z powyższych odnośników a instalacja języka Nim powinna zakończyć się pomyślnie.
Później sprawdzimy czy instalacja przebiegła pomyślnie.

Jeżeli używasz systemu z rodziny GNU/Linux, jest duża szansa, że twoja dystrybucja posiada język Nim w swoim menadżeże pakietów.
eżeli instalujesz ęzyk w ten sposób, upewnij się, że jest to najnowsza wersja (sprawdź na stronie która wersja jest najnowsza), w przeciwnym wypadku zainstaluj język korzystając w którejś z metod przedstawionych wcześniej.

W tym kursie będziemy używać wersji stabilnej 0.19.0. Tematy omawiane w kursie nie powinny się znacząco zmienić w przyszłych wersjach języka.




== Instalacja dodatkowych narzędzi

Możesz pisać swój kod w dowolnym edytorze tekstu, a później skompilować i uruchomić program prosto z terminala.
Jeśli potrzebujesz podświetnenie składni i opcji uzupełniania kodu istnieją wtyczki dla popularnych edytorów kodu, które dostarczają te funkcjonalności.

Autor używa edytora https://code.visualstudio.com/[VS Code], razem z https://marketplace.visualstudio.com/items?itemName=kosz78.nim[tym rozszerzeniem] który dostarcza podświetnenie składni oraz uzupełnianie kodu, oraz https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner[rozszerzenie Code Runner] dla szybszej kompilacji i uruchamiania.

Jeżeli używasz innych edytorów kodu, zobacz https://github.com/nim-lang/Nim/wiki/Editor-Support[wiki] aby sprawdzić dostępne wsparcie.




== Testowanie instalacji

Aby sprawdzić czy instalacja przebiegła pomyślnie, napiszemy program który jest tradycyjnie używany na początku nauki: https://en.wikipedia.org/wiki/%22Hello,_World!%22_program[Witaj Świecie].

Drukowanie (to jest: wyświetlanie na ekranie; nie na papierze z wykorzystaniem drukarki) frazy `Hello World!` w języku Nim jest proste i nie wymaga żadnego zbędnego kodu.

W nowym pliku tekstowym nazwanym na przykład  `helloworld.nim` potrzebujemy napisać tylko jedną linijkę kodu:

[source]
.helloworld.nim
----
include::code/helloworld.nim[]
----

NOTE: Fraza, którą chcesz wyświetlić musi poprzedzać polecenie `echo` i być wewnątrz znaków cudzysłowu (").

Najpierw musimy skompilować nasz program, a następnie uruchomić go aby sprawdzić czy działa zgodnie z oczekiwaniami.

Otwórz terminal w tym samym katalogu gdzie znajduje się plik z kodem (W systemach GNU/Linux możesz użyć "Otwórz terminal tutaj" jeżeli klikniesz PPM na nazwie katalogu w menadźeże plików, w systemie Windows powinieneś użyć Shift + PPM aby wyświetlić menu z dostępem do linii komend).

Kompilacji dokonujemy wpisując w oknie terminala:
[source, terminal]
----
nim c helloworld.nim
----

Po pomyślnej kompilacji możemy uruchomić nasz program.
W systemch GNU/Linux program uruchamiamy wpisując `./helloworld` w oknie terminala, a w systemie Windows wpisując `helloworld.exe`.

Jest również możliwość przeprowadzenia kompilacji i uruchomienia programu jednym poleceniem.
Musimy wpisać:
[source, terminal]
----
nim c -r helloworld.nim
----

NOTE: `c` mówi kompilatorowi aby skompilował plik z kodem, a `-r` aby uruchomił gotowy plik programu. +
Aby zobaczyć wszystkie opcje kompilatora, wpisz `nim --help` w oknie terminala.

Jeżeli używasz VSCode razem z rozszerzeniem Code Runner , naciśnij `Ctrl+Alt+N` a twój plik zostanie skompilowany i uruchomiony.

Którykolwiek sposób wybierzesz aby uruchomić swój program, po chwili w oknie terminala powinieneś zobaczyć:
[source, output]
----
Hello World!
----

Gratulacje! Właśnie uruchomiłeś swój pierwszy program w języku Nim!

Teraz, kiedy wiesz już jak wyświetlać rzeczy na ekranie (używając polecenia`echo`), skompiluj plik z kodem (wpisując `nim c nazwaProgramu.nim` w swoim terminalu), i urruchom go (różnymi sposobami).

Możemy już zacząć poznawanie podstawowych elementów które pomogą nam w pisaniu prostych programów w języku Nim.
